# TODO: Try to figure out how to use GitHub Secrets in docker compose file
services:
  db:
    image: "postgres:15.2-alpine"
    restart: always
    container_name: "viatab-db-container"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db/postgres.env

  backend:
    image: "viatab-backend:latest"
    build:
      context: ./backend
    container_name: "viatab-backend-container"
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - db/spring_db.env

  frontend:
    image: "viatab-frontend:latest"
    build:
      context: ./frontend
    container_name: "viatab-frontend-container"
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db:
    driver: local
