services:
  db:
    image: "postgres:15.2-alpine"
    restart: always
    container_name: "viatab-db-container"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=viatab-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    image: "viatab-backend:latest"
    build:
      context: ./backend
    container_name: "viatab-backend-container"
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/viatab-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: "viatab-frontend:latest"
    build:
      context: ./frontend
    container_name: "viatab-frontend-container"
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db:
    driver: local
