apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-viatab
  labels:
    app: k8s-viatab
spec:
  replicas: 2 # pod count
  selector:
    matchLabels:
      app: k8s-viatab
  template:
    metadata:
      name: k8s-viatab
      labels:
        app: k8s-viatab
    spec:
      containers:
        - name: k8s-viatab
          image: k8s-viatab:v2.15.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
